export const toolCategoriesSeed = [
  {
    id: "audio",
    slug: "audio",
    name: "Audio",
    description: "Audio processing tools",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "video",
    slug: "video",
    name: "Video",
    description: "Video processing tools",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "image",
    slug: "image",
    name: "Image",
    description: "Image processing tools",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "pdf",
    slug: "pdf",
    name: "PDF",
    description: "PDF tools",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "file",
    slug: "file",
    name: "File",
    description: "File utilities",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "seo",
    slug: "seo",
    name: "SEO",
    description: "SEO tools",
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "ai",
    slug: "ai",
    name: "AI",
    description: "Artificial Intelligence tools",
    sortOrder: 7,
    isActive: true,
  },
];
